name: Pacman CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:  
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Pacman
        run: |
          echo Hello World
          javac -cp "junit-4.10.jar:." src/java/pacman/*.java 
