name: Pacman CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:  
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Build Pacman
        run: |
          echo Hello World
          cd Projects/P2
          ./gradlew build testClasses -x test
  
  pacman_valid_moves:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: pacman valid moves
        run: |
          cd Projects/P2
          ./gradlew test --parallel --tests TestPacManValidMoves

  ghost_move:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: ghost move
        run: |
          cd Projects/P2
          ./gradlew test --parallel --tests TestGhostMove

  map_attack:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: map attack
        run: |
          cd Projects/P2
          ./gradlew test --parallel --tests TestMapAttack

  # adding tests for missing functions
  pacman_move:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: pacman move
        run: |
          cd Projects/P2
          ./gradlew test --parallel --tests TestPacManMove

  ghost_valid_moves:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: ghost valid moves
        run: |
          cd Projects/P2
          ./gradlew test --parallel --tests TestGhostValidMoves

  map_get_loc:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: map get loc
        run: |
          cd Projects/P2
          ./gradlew test --parallel --tests TestMapGetLoc

  map_eat_cookie:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: map eat cookie
        run: |
          cd Projects/P2
          ./gradlew test --parallel --tests TestMapEatCookie
  
  pacman_is_ghost_in_range:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: pacman is ghost in range
        run: |
          cd Projects/P2
          ./gradlew test --parallel --tests TestGhostInRange

  ghost_attack:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: ghost attack
        run: |
          cd Projects/P2
          ./gradlew test --parallel --tests TestGhostAttack
  
  map_move:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: map move
        run: |
          cd Projects/P2
          ./gradlew test --parallel --tests TestMapMove
  
  ghost_pacman_in_range:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: ghost pacman in range
        run: |
          cd Projects/P2
          ./gradlew test --parallel --tests TestPacManInRange


  pacman_consume:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: pacman consume
        run: |
          cd Projects/P2
          ./gradlew test --parallel --tests TestPacManConsume



  

