name: pacman_main

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      -name: Compile Pacman 
      -uses: actions/checkout@v2
      run: gradle build
      
