name: Pacman CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:  
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Build Pacman
        run: |
          echo Hello World
          cd Projects/P2/app/src/test/java/pacman
          javac -cp ".:junit-4.10.jar" *.java
