name: Pacman CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:  
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Build Pacman
        working-directory: Projects/P2
        run: |
          echo Hello World
          gradle build
